codecov:
  require_ci_to_pass: no

# coverage of each PR must be at least 85% and must not be negative
coverage:
  status:
    project:
      default:
        informational: true
      backend:
        target: 37%
        threshold: 3%
        flags: 
          - backend
    patch:
      default:
        informational: true
      backend: 
        target: 85%
        threshold: 5%
        flags: 
          - backend

flags:
  backend:
    carryforward: true

github_checks:
  annotations: false

comment: 
  layout: "diff, flags, files"
  behavior: default
